### PR TITLE
1386 fix

### PR DESCRIPTION
**Pull request by ldebruijn**
Properly alignment of the text in the Time Series Chart. Cleanup of the CSS (Less).

Old situation where the text aligned to the top:
old

New situation where the text is properly aligned to the bottom:
new

Tested in Chrome, Firefox and IE. Haven't had the possibility to test in Safari, but I suspect no problems.
Succesully ran locally and on Azure.

It's a small fix, but it bothered me. Therefore this pull request.

### CODE REVIEW

**Comment by saekow** [comment]
Thank you!

**Comment by alterm4nn** [comment]
@ldebruijn Nice catch, thanks!

What I see that title is still a 1-2 pixels upper than the rest of the text. Can you please fix that also in you pull request?
image

**Comment by ldebruijn** [comment]
@alterm4nn , new commit. again, tested in all the above mentioned browsers and platforms.

New situation:
alignment

**Comment by alterm4nn** [comment]
Thanks for this!

**Pull request merged**
