### PR TITLE
Fix for #1386

### PR DESCRIPTION
**Pull request by ldebruijn**
Fixed the #1386 issue with more elegance. The CSS fix has been moved to the appropriate less files and the generation and manipulation of CSS both inline and in JavaScript has been removed.

### CODE REVIEW

**Comment by alterm4nn** [comment]
@neilcresswell, can you check on mac please?

**Comment by NeilCresswell** [comment]
Truncated in Safari 7 on OSX Mavericks.
Please see screenshot.
temp

**Comment by alterm4nn** [comment]
@ldebruijn Can you please make first column wider so preloaded content will fit?

**Comment by ldebruijn** [comment]
Sure thing! Coming up in a bit =].

**Comment by ldebruijn** [comment]
@alterm4nn as promised. Made the first column wider to fit the text.

**Comment by NeilCresswell** [comment]
Works great OSX Mav Safari 7.

**Pull request merged**
